### ISSUE TITLE
Support for ClamWIn and Clam AV 

### ISSUE THREAD

**Issue by smartmeter** [dcr26/ExampleMVCVirusScanner#2]
Hello can you show me how to integrate Clamwin or clamAV. Sophos is too pricey :)

nice work by the way - I like how you are integrating the file stream before save! :+1:

**Comment by dcr26** [comment]
It should be quite clear in the sample code smartmeter, if you have problems, let me know where you get stuck

**Comment by smartmeter** [comment]
ok will do, I am trying

**Comment by smartmeter** [comment]
:+1:
